# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
  - job: run_test
    timeoutInMinutes: 1

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - script: docker build -f Dockerfile -t docker_failed_image .
        displayName: 'docker build'
        timeoutInMinutes: 0
        continueOnError: true
      - script: docker login -u $(DockerHub_user) -p $(DockerHub_password)
      # Try to tag the latest failed image we ran if it failed
      - script: docker tag `docker ps -a -l -q | xargs docker commit | awk -F":" '{print $2}'` $(DockerHub_user)/docker_failed_image:latest
      # Push it, if it failed
      - script: docker push $(DockerHub_user)/docker_failed_image
